### ISSUE TITLE
Finaliser le courriel aux participants et le questionnaire

### ISSUE THREAD

**Issue by emchateau** [tei-fr/formationEnc2017-02#2]
Hello @lb42,

J‘ai repris le questionnaire et fait un brouillon de courriel aux participants.
Tu trouveras cela dans le fichier https://github.com/tei-fr/formationEnc2017-02/blob/master/preparation.md

Peux-tu jeter, s’il te plaît, y jeter un œil et me dire ce que tu en penses.
Il me semble que nous pourrions leur demander de faire un ou deux exercice avec ODD, que suggères-tu à cet égard ?

Je vais m’occuper de traduire les tutoriels dont tu m‘as parlé (http://teic.github.io/PDF/) d’ici la semaine prochaine.

Amitiés,
Emmanuel

**Comment by lb42** [comment]
Oui, ca marche. Mais il faut le convertir  en Google questionnaire assez vite si on souhaite avoir le temps de digerer les reponses! (a quel propos, je ne vois pas de date limite pour les reponses).  Pour les exercices en avance, je crains ne pas avoir pas le temps de les preparer avant l'envoie du questionnaire, a moins que tu aies deja qqchose en tete.  Les participants auront suffisamment de boulot avec le qnaire, me sembletil.

**Comment by lb42** [comment]
Toujours pas de nouvelles?
