### ISSUE TITLE
Traduire les tutoriels ODD

### ISSUE THREAD

**Issue by emchateau** [tei-fr/formationEnc2017-02#3]
Traduire les tutoriels http://teic.github.io/PDF/ en vue de la formation.

**Comment by emchateau** [comment]
Je vais essayer de m’y coller ce WE dans le cas où nous voudrions leur demander de faire ces exercices avant la formation. 
Peux-tu, s’il te plaît @lb42 ,  me donner le lien vers les fichiers TEI de manière à ce que je puisse traduire les sources ?

**Comment by lb42** [comment]
Ils sont tous dans le dossier Documents/pureODD du repertoire https://github.com/TEIC/TEI
par ex https://raw.githubusercontent.com/TEIC/TEI/dev/Documents/pureODD/howtoChain.xml
NB ce ne sont que des esquisses de brouillons: sans doute tu trouveras des erreurs ou des simplifications eventuelles en les traduisant
Et il nous manque toujours une introduction basique...

**Comment by emchateau** [comment]
- [x] How to chain
- [x] Purify Doc (in progress)
- [x] Pure ODD tutorial
