### ISSUE TITLE
Finaliser le programme

### ISSUE THREAD

**Issue by lb42** [tei-fr/formationEnc2017-02#5]
jour 1

- En 2015 je ne pouvais pas assister la premiere journee; je propose que nous profitions cette fois ci de ma presence! je peux prendre en charge les 2 recapitulations de la TEI (03-organisation et 04-personnalisation) si ca te gene pas. D'autant plus qu'ils ont besoin d'une mise a jour (aucun mention des construction pureODD)

 - le titre de la session "installation du module ODD" n'est pas correcte. Il ne s'agit pas d'un module ODD, mais d'un framework oXygen; d'ailleurs je pense que ce framework est bien installe. J'ai corrige en "Verification d'installation d'Oxygen" et reduit de 60 a 30 minutes

 - qu'est-ce que tu envisages pour la "TP02 : Premier exercice d’encodage de ses documents" ? en tout cas je l'elargis a une heure

 - c'est quoi la "TP03 Quiz TEI" ?

jour 2

11-1130 : "De quoi a-t-on besoin ?" : c'est une discussion des projets des participants? ou quoi?

J'ai re-numerote les 3 "talks" pour continuer la sequence, donc l'ancien "talk-01-init" devient "05-initODD" et ainsi de suite. 

L'intervention 16h-17h "TEI sous le capot" c'etait quoi? La premiere partie de lintervention du 3eme jour peutetre? Et qu'est ce que tu entendais par la mention "Pure ODD" (17h-1730)? Maintenant, pure ODD est totalement integree, donc je preferais ne pas le separer du reste : ce qui implique que je dois mettre a jour l'intervention "TEI sous le capot".

jour 3

a part la session initiale (0930-11h), ils vont bosser sur leurs projets en binome. On avait propose de varier cela avec deux "focus" mais les sujets sont a decider. Nous avons qqs diapos pour un focus sur les images, et un autre sur les pointeurs pas encore traduit en francais. D'autres sont envisageables.

jour 4

semble  imprecis, et risque de repeter trop des choses deja abordees.
il serait peut etre mieux de diviser en petites portions le talk 09-advanced.xml, parce qu'il traite de plusieurs sujets.

**Comment by emchateau** [comment]
Hello @lb42 ,
Je re-regardais le programme général pour la finalisation. A-t-on encore besoin le premier jour, de 14h30-15h00, d’avoir TP01 : Vérification d’installation correcte d’oXygen ?
On a vérifié que c’était bon avec la version 17 et 18 pour teiOdd, etc.
Je reprends l’ensemble et te reviens sur le programme.

**Comment by lb42** [comment]
Ca depend : sil y a des gens qui bossent avec leur propre ordi ? Mais, oui, en effet, je pense qu'on peut supprimer cette session.

**Comment by lb42** [comment]
Je viens de modifier le programme : faire un pull pour t'assurer que c'est ok
