### ISSUE TITLE
Permettre l’auto-complétion du type avec le schéma

### ISSUE THREAD

**Issue by emchateau** [tei-fr/formationEnc2017-02#6]
Hello @lb42,
Le schéma RelaxNG généré par l’odd pour les diapositives formationEnc2017-02/schemas/teiSlides.odd (que j’ai un peu modifié dont son nom et id) n’offre pas l’auto-complétion pour les valeurs énumérées pour @type sur &lt;div> dans oXygen. Est-ce un bug général de la transformation oddtorelaxng, ou bien un bug dans notre odd ?

**Comment by lb42** [comment]
C'est un bug dans l'ODD et je l'ai corrigé.  Mais remarques: tu n'auras pas de auto-completion sauf si la valeur de lattribut concerné deviendra closed: qui ne serait pas optimal pour les div qui ne sont pas typés

**Comment by emchateau** [comment]
Ne peut-on pas avoir une liste ouverte et l’auto-complétion ? Avant c’était possible car je l’utilisais pour les valeur de type.
