### ISSUE TITLE
Prévoir l’installation de oddByExample

### ISSUE THREAD

**Issue by emchateau** [tei-fr/formationEnc2017-02#7]
Salut @lb42,
Je suis en train de traduire ton tutoriel sources/howtoGenerate.xml
Pour information, le répertoire `tools` indiqué n’est pas présent dans le framework TEI distribué avec la dernière version d’oXygen (version 18). Même si je ne suis pas certain que les licences de l’ENC aient été mises à jour depuis l’année dernière.
Mais il faut donc sans doute prévoir l’installation de quelque chose. Il y a dans le répertoire encore l’ancienne procédure.

**Comment by lb42** [comment]
Il y avait une erreur dans la source! merci de l'avoir découverte;  je l'ai corrigée sur le repo TEI.

Le chemin correct pour oxyGen est le suivant: 
 **${frameworks}/tei/xml/tei/stylesheet/tools/oddbyexample.xsl**

Ca fonctionne pour moi avec une ancienne version (17) d'oxyGen sans installation

**Comment by emchateau** [comment]
C'est également bon avec la version 18, désolé je ne l'avais pas trouvé hier.
